# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.
# This workflow is managed by gh actions-lock.

name: CI
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1' # Latest stable
        os:
          - ubuntu-latest
        include:
          - version: '1'
            os: macOS-latest
          - version: '1'
            os: windows-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: julia-actions/setup-julia@v3.0.2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3.3.0
      - uses: julia-actions/julia-buildpkg@v1.7.0
      - uses: julia-actions/julia-runtest@v1.12.0
